### ISSUE TITLE
When you apply a selinux::fecontext rule with recurse false, then later change it to true, that change doesn't get made

### ISSUE THREAD

**Issue by thomasvs** [thias/puppet-selinux#3]
I confirmed after applying with

  semanage fcontext /var/log/couchdb-hoodie --list | grep hoodie

that the rule was still the old rule.

I had to manually delete it with:

  semanage fcontext --delete /var/log/couchdb-hoodie

**Comment by thias** [comment]
Yeah... quite a known limitation. Basic ensure => absent isn't supported either... pull requests welcome! :-)
